### ISSUE TITLE
Documentation: Add React + JavaScript Example

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#10]
## What should be changed?

- [X] An example is missing
- [ ] Existing documentation needs to be extended
- [ ] Something else, state below:

## Description

Create an example of this library being used similar to what is on this codesandbox: https://codesandbox.io/s/react-in-out-textarea-typescript-react-egi57?file=/src/ExampleComponent.tsx

1. Create another codesandbox on a pure React template
2. Add `react-in-out-textarea` as dependency
3. Integrate it similar to the other example

Create another codesandbox without TypeScript support and add it to the README.

## Files involved

* `README.md`

**Comment by devcer** [comment]
@igeligel Can I pick this and work on it? Assign this to me.

**Comment by igeligel** [comment]
Yeah, feel free to do it. Assigning you now. If you need any help, feel free to reach out to me :)

**Comment by devcer** [comment]
I created the required sandbox -> https://codesandbox.io/s/react-in-out-textarea-javascript-react-kcl37
Will test and submit a PR in a few hours.

**Comment by igeligel** [comment]
This seems perfect 👌 Thanks a lot
