### ISSUE TITLE
Refactoring Textarea styled component

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#100]
## Type of Change

- [ ] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [X] Extract React component
- [ ] Remove duplicate code

## Description

The `<Textarea>` component should live in their own file.

## Code Before

<details>
  <summary>./index.tsx</summary>
  
  ```tsx
  const Textarea = styled(TextareaAutosize)<ExampleTextProps>`
    // ...
  `;
  ```
</details>

## Code Expected after Refactoring

<details>
  <summary>./styled/textarea.ts</summary>
  
  ```tsx
  type ExampleTextProps = {
    // ...
  };

  export const Textarea = styled(TextareaAutosize)<ExampleTextProps>`
    // ...
  `;
  ```
</details>

<details>
  <summary>./index.tsx</summary>
  
  ```tsx
  import { Textarea } from './styled/Textarea';

  // Same usage in React code
  ```
</details>

## Files involved

* `src\index.tsx`
* and you need to create a new file

**Comment by emmalearnscode** [comment]
Can I work on this issue?

**Comment by igeligel** [comment]
@emmalearnscode Sure thing. I have assigned the issue to you now. If you need any help with setting up the code base or have any other question, feel free to reach out to me.
