### ISSUE TITLE
Documentation: Add documentation for onCopy parameter

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#102]
## What should be changed?

- [ ] An example is missing
- [X] Existing documentation needs to be extended
- [ ] Something else, state below:

## Description

The `onCopy` method you can pass to the component is not documented and should be documented in the README.md. It is an optional field and is simply a function you can pass to the component similar to:

```tsx
import { InOutTextarea } from 'react-in-out-textarea'

import { InOutTextarea } from "react-in-out-textarea";

export const LoremIpsum = () => {
  return (
    <InOutTextarea
      // wadwadwad
      onCopy={() => {
        alert("You have copied something");
      }}
    />
  );
};
```

The ticket expects that this table is extended:

![chrome_GrGbQWBvFC](https://user-images.githubusercontent.com/12736734/135713326-60abb501-db6d-446a-a847-0324d62edc20.png)

## Files involved

* `README.md`

**Comment by wsameer** [comment]
@igeligel can I make this change?

**Comment by igeligel** [comment]
Hey @wsameer , sure thing. I will assign it to you.
