### ISSUE TITLE
Refactoring MidCaseBar

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#11]
## Type of Change

- [ ] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [ ] Extract React component
- [ ] Remove duplicate code
- [X] Other

## Description

Currently `MidCaseBar` is used in `./src/index.tsx` but actually a `<Spacer />` component should exist to handle that.

## Code Before

```tsx
// ...
const MidCaseBar = styled.div``;
// ...

export const InOutTextarea: FC<Props> = (props) => {
  return (
    <>
      {/* ... */}
      <LeftCaseBar>{/* ... */}</LeftCaseBar>
      <MidCaseBar>
        <div style={{ width: "40px" }}>{/* <IconRefreshCw /> */}</div>
      </MidCaseBar>
      <RightCaseBar>{/* ... */}</RightCaseBar>
      {/* ... */}
    </>
  );
};
```

## Code Expected after Refactoring

```tsx
// ...
import { Spacer } from "./Spacer";

export const InOutTextarea: FC<Props> = (props) => {
  return (
    <>
      {/* ... */}
      <LeftCaseBar>{/* ... */}</LeftCaseBar>
      <Spacer vertical />
      <RightCaseBar>{/* ... */}</RightCaseBar>
      {/* ... */}
    </>
  );
};

```

## Files involved

* `./src/index.tsx`
* `./src/Spacer.tsx` - needs to be created

**Comment by codeR49** [comment]
i want to have a shot to this

**Comment by igeligel** [comment]
@codeR49 Feel free to do this. I will assign you for now :) If you have any problems setting up the environment or any other problem feel free to contact me - Happy to help.

And in any case, you have any improvement, just make a comment here, appreciate it. Cheers, Kev

**Comment by igeligel** [comment]
Hey @codeR49, any update on this? I will unassign you from now.

**Comment by GabrielFalcom** [comment]
I would like to contribute to this issue.

**Comment by GabrielFalcom** [comment]
Spacer vertical prop = 40px of height?

**Comment by igeligel** [comment]
Hey @GabrielFalcom. Do you still want to take the issue? I will assign you for now. How you design the Spacer is up to you. If you think a prop makes sense, then let us use that format.
