### ISSUE TITLE
Refactoring Root React Fragment

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#12]
## Type of Change

- [X] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [ ] Extract React component
- [ ] Remove duplicate code

## Description

Currently, the main component is wrapped in a [React fragment](https://reactjs.org/docs/fragments.html). It should not be wrapped.

## Code Before

```tsx
// ...

export const InOutTextarea: FC<Props> = (props) => {
  return (
    <>
      <ConvertCard>{/* ... */}</ConvertCard>
    </>
  );
};
```

## Code Expected after Refactoring

```tsx
// ...

export const InOutTextarea: FC<Props> = (props) => {
  return <ConvertCard>{/* ... */}</ConvertCard>;
};

```

## Files involved

* `./src/index.tsx`

**Comment by katieraby** [comment]
Can I take this issue on please?

**Comment by igeligel** [comment]
Thanks for reaching out. It is yours now. Will assign it. If you have any trouble with setting up the environment or any other problem with contributing. Feel free to reach out to me :)

**Comment by katieraby** [comment]
https://github.com/igeligel/react-in-out-textarea/pull/24
Also incorporates a minor fix out of scope to fix color value from #white to white.

**Comment by igeligel** [comment]
Basic usage: @all-contributors please add @katieraby for code

**Comment by igeligel** [comment]
Closing this issue. Thanks again for your contribution. Feel free to contribute to another issue if you like :)
