### ISSUE TITLE
Refactoring LeftCaseBar & RightCaseBar

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#13]
## Type of Change

- [ ] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [X] Extract React component
- [ ] Remove duplicate code

## Description

Currently, in the code there is a `LeftCaseBar` and `RightCaseBar`. These should be unified to a standalone styled-component called `CaseBar`. Actually the code is not so different. Just including a `justify-content: space-between;` and a media-query that can be removed.

## Code Before

```tsx
const LeftCaseBar = styled.div`
  flex: 1;
  display: flex;
  color: #14213d;
  justify-content: space-between;
  overflow: hidden;
  position: relative;
`;

// ...

const RightCaseBar = styled.div`
  flex: 1;
  display: flex;
  color: #14213d;
  overflow: hidden;
  position: relative;
  @media (max-width: 576px) {
    flex-direction: column;
  }
`;

export const InOutTextarea: FC<Props> = (props) => {
  // ...
  return (
    <>
      {/* ... */}
      <LeftCaseBar>{/* ... */}</LeftCaseBar>
      <RightCaseBar>{/* ... */}</RightCaseBar>
      {/* ... */}
    </>
  );
};
```

## Code Expected after Refactoring

```tsx
// SideBar.ts
const SideBar = styled.div`
  flex: 1;
  display: flex;
  color: #14213d;
  overflow: hidden;
  position: relative;
`;

// index.ts
import { SideBar } from "./SideBar";

export const InOutTextarea: FC<Props> = (props) => {
  // ...
  return (
    <>
      {/* ... */}
      <SideBar>{/* ... */}</SideBar>
      <SideBar>{/* ... */}</SideBar>
      {/* ... */}
    </>
  );
};
```

## Files involved

* `./src/SideBar.ts`
* `./src/index.tsx`

**Comment by xen0m29** [comment]
can i take this?

**Comment by xen0m29** [comment]
can i take this?

**Comment by igeligel** [comment]
Yes, you can take that @xen0m29, I assigned the ticket to you. If you have any trouble setting up an environment or any other problem, feel free to reach out to me :)
