### ISSUE TITLE
Refactoring Unify LeftContent and RightContent

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#15]
## Type of Change

- [ ] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [X] Extract React component
- [ ] Remove duplicate code

## Description

Currently, there are two `styled-components` called `LeftContent` and `RightContent` that are basically doing the same. A Pull Request should be created that unifies these two. The background-color for theming can be removed.

## Code Before

```tsx
// index.tsx

// ...

const LeftContent = styled.div`
  flex: 1;
`;

// ...

const RightContent = styled.div`
  flex: 1;
  background-color: ${(props) =>
    props.theme.main === "dark" ? "rgb(24, 37, 66)" : "rgb(249, 250, 250)"};
`;

// ...

export const InOutTextarea: FC<Props> = (props) => {
  // ...
  return (
    <>
      {/* ... */}
      <LeftContent>{/* ... */}</LeftContent>
      <RightContent>{/* ... */}</RightContent>
      {/* ... */}
    </>
  );
};
```

## Code Expected after Refactoring

```tsx
// Content.ts
export const Content = styled.div`
  flex: 1;
`;

// index
// ...
import { Content } from "./Content";
// ...

export const InOutTextarea: FC<Props> = (props) => {
  // ...
  return (
    <>
      {/* Insted of LeftContent and RightContent */}
      <Content>{/* ... */}</Content>
      <Content>{/* ... */}</Content>
      {/* ... */}
    </>
  );
};
```

## Files involved

* [`./src/index.tsx`](https://github.com/igeligel/react-in-out-textarea/blob/master/src/index.tsx)
* `./src/Content.ts` - this needs to be created

**Comment by SheW0lf** [comment]
I'll snag this one too 😸

**Comment by igeligel** [comment]
Sure thing, will assign you now 👍
