### ISSUE TITLE
Continuous Integration & Continuous Delivery: Workflow check for Pull Requests

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#18]
## Type of Change

- [X] Integration Pipeline
- [ ] Delivery Pipeline
- [ ] Other:

## Description

Create a workflow that looks similar to the main workflow in this repository and checks Pull Requests for validity. A build and tests should get executed.

## Code Before

No code regarding Pull Request checks exists :(

## Code After

```bash
name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true
```

This code should exist. It is super similar to what is included in [`./.github/workflows/main.yml`](https://github.com/igeligel/react-in-out-textarea/blob/master/.github/workflows/main.yml) and should ideally be reused if possible. If not, also not too bad.

## Files involved

- `./.github/workflows/pull-request.yml` - does not exist yet

**Comment by devcer** [comment]
@igeligel I would like to work on this. Can you assign this to me? Been setting this up on my personal repos. would be a learning experience for me.

**Comment by devcer** [comment]
@igeligel Submitted a PR. Let me know if any changes are required.
