### ISSUE TITLE
Documentation: Update README

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#19]
## What should be changed?

- [ ] An example is missing
- [ ] Existing documentation needs to be extended
- [X] Something else, state below:

README Update

## Description

The README should include a features section similar to the one in [ag-grid](https://github.com/ag-grid/ag-grid#features).

Include features like:

- Selection of input and output type
- Textarea for input and output
- Fully controllable
- Additional like styling and so on

## Files involved

* [`README.md`](https://github.com/igeligel/react-in-out-textarea/blob/master/README.md)

**Comment by katieraby** [comment]
Can I take this one on please? 😄

**Comment by igeligel** [comment]
@katieraby Sure thing will assign this ticket to you.

**Comment by katieraby** [comment]
https://github.com/igeligel/react-in-out-textarea/pull/37

**Comment by igeligel** [comment]
Thanks a lot for your contribution 👍
