### ISSUE TITLE
Documentation: Add installation instructions to README

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#20]
## What should be changed?

- [ ] An example is missing
- [X] Existing documentation needs to be extended
- [ ] Something else, state below:

## Description

Under the Usage section in the README, an installation instruction should be given. Create a sub heading + a collapsible installation instruction for either `yarn` and `npm`, similar to [cogo-toast](https://github.com/Cogoport/cogo-toast) ([`yarn`](https://github.com/Cogoport/cogo-toast#install-via-yarn) / [`npm`](https://github.com/Cogoport/cogo-toast#install-via-npm)).

The collapsible area can be done similar to:

```md
<details>
 <summary>npm</summary>

```bash
npm command
\```

</details>
```

## Files involved

* [`README.md`](https://github.com/igeligel/react-in-out-textarea/blob/master/README.md)

**Comment by hambali999** [comment]
Hi can i take over this issue? This is my first hacktobefest as a starter :)
