### ISSUE TITLE
Documentation: Create a Props Section in the README

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#25]
## What should be changed?

- [ ] An example is missing
- [X] Existing documentation needs to be extended
- [ ] Something else, state below:

## Description

The [README.md](https://github.com/igeligel/react-in-out-textarea/blob/master/README.md) currently has examples, but the props can be explained in the [README.md](https://github.com/igeligel/react-in-out-textarea/blob/master/README.md). The section should be shown after the Usage section and should have `Props` as heading.

The table should look like the following:

| Name | Type | Description |
| -- | -- | -- |
| inValue | string | The value that is shown on the left-handed side. |
| ... | ... | ... |

The table should include all values of the [exported interface here](https://github.com/igeligel/react-in-out-textarea/blob/f5cb6d1d9ed46b0a5b4ce921dbc0264866e8488a/src/index.tsx#L203-L211).

## Files involved

* [`README.md`](https://github.com/igeligel/react-in-out-textarea/blob/master/README.md)

**Comment by xen0m29** [comment]
can i take this?

**Comment by igeligel** [comment]
Hey @xen0m29, there is another Pull Request by @aman601 already [here](https://github.com/igeligel/react-in-out-textarea/pull/27). Feel free to review it though.
