### ISSUE TITLE
Refactoring MoreOptionsIconContainer in onClick Handler

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#47]
## Type of Change

- [ ] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [ ] Extract React component
- [ ] Remove duplicate code
- [X] Extract Code

## Description

No inline function handler for the `MoreOptionsIconContainer` onClick handler for the inOptions should be used. This issue is just dealing with the **in handler**.

By not inlining the function it improves performance because the function does not get registered as anonymous function every time the component is rendered.

## Code Before

```tsx
// ./src/index.tsx
return () => {
  // ...
  return (
    <MoreOptionsIconContainer
      ref={inOptionsMenuRef}
      onClick={() => {
        setShowAdditionalOutOptions(false);
        setShowAdditionalInOptions(!showAdditionalInOptions);
      }}
    >
      {!showAdditionalInOptions && <IconChevronDown />}
      {showAdditionalInOptions && <IconChevronUp />}
    </MoreOptionsIconContainer>
  );
};
```

## Code Expected after Refactoring

```tsx
// ./src/index.tsx
return () => {
  // ...
  const onInMoreOptionsClick = useCallback(() => {    
    setShowAdditionalOutOptions(false);
    setShowAdditionalInOptions(!showAdditionalInOptions);
  }, [showAdditionalInOptions]);

  // ...
  return (
    <MoreOptionsIconContainer
      ref={inOptionsMenuRef}
      onClick={onInMoreOptionsClick}
    >
      {!showAdditionalInOptions && <IconChevronDown />}
      {showAdditionalInOptions && <IconChevronUp />}
    </MoreOptionsIconContainer>
  );
};
```

## Files involved

* `./src/index.tsx`

**Comment by binkpitch** [comment]
Can I take this issue?

**Comment by igeligel** [comment]
Yes of course, i will assign you now.

There is also a mistake in naming the existing function in `index.tsx` with the function `onOutMoreOptionsClick`. Hopefully you can spot that and fix it as well. Cheers, Kevin
