### ISSUE TITLE
Refactoring MoreOptionsIconContainer out onClick Handler

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#48]
## Type of Change

- [ ] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [ ] Extract React component
- [ ] Remove duplicate code
- [X] Extract Code

## Description

No inline function handler for the `MoreOptionsIconContainer` onClick handler for the `outOptions` should be used. This issue is just dealing with the **out handler**.

By not inlining the function it improves performance because the function does not get registered as an anonymous function every time the component is rendered.

## Code Before

```tsx
// ./src/index.tsx
return () => {
  // ...
  return (
    <MoreOptionsIconContainer
      right
      ref={outOptionsMenuRef}
      onClick={() => {
        setShowAdditionalInOptions(false);
        setShowAdditionalOutOptions(!showAdditionalOutOptions);
      }}
    >
      {!showAdditionalOutOptions && <IconChevronDown />}
      {showAdditionalOutOptions && <IconChevronUp />}
    </MoreOptionsIconContainer>
  );
};
```

## Code Expected after Refactoring

```tsx
// ./src/index.tsx
return () => {
  // ...
  const onOutMoreOptionsClick = () => {
    setShowAdditionalInOptions(false);
    setShowAdditionalOutOptions(!showAdditionalOutOptions);
  };

  // ...
  return (
    <MoreOptionsIconContainer
      right
      ref={outOptionsMenuRef}
      onClick={onOutMoreOptionsClick}
    >
      {!showAdditionalOutOptions && <IconChevronDown />}
      {showAdditionalOutOptions && <IconChevronUp />}
    </MoreOptionsIconContainer>
  );
};
```

## Files involved

* `./src/index.tsx`

**Comment by silltho** [comment]
i would like to work on this.
