### ISSUE TITLE
Documentation: maxContentLength

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#49]
## What should be changed?

- [ ] An example is missing
- [X] Existing documentation needs to be extended
- [ ] Something else, state below:

## Description

In #45 the feature for variable content length was merged but was not documented. Let us document that.

Add it to the props section in the README.md ([link](https://github.com/igeligel/react-in-out-textarea#props)). Also, add another column to the table that is called required and has the values ✔️ for everything except `maxContentLength`, that is added, and should have the value ❌ since it is not required.

Also, under the Feature section the `Variable content length` should be shown as fully ready now.

## Files involved

* `README.md`

**Comment by ggolubic** [comment]
Hey, can I take this?
