### ISSUE TITLE
Feature: Mobile Design Setup

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#69]
## Type of Feature

- [ ] API Extension
- [ ] UI Feature
- [X] other

Add story on storybook for mobile support

## How would it look like

![chrome_2020-10-13_22-33-24](https://user-images.githubusercontent.com/12736734/95913169-1f8c0600-0da4-11eb-8187-d2f51d070d85.png)

Use the Storybook Viewport plugin: https://storybook.js.org/docs/react/essentials/viewport. The `maxWidth` example below is suboptimal.

```tsx
export const Mobile = (props?: Partial<Props>) => {
  const [inValue, setInValue] = useState<string>("Hello");
  const [inOptions, setInOptions] = useState<InOptions>([
    {
      name: "English",
      active: false,
    },
    // Add more options
  ]);

  const [outOptions, setOutOptions] = useState<OutOptions>([
    {
      name: "English",
      active: true,
      activeClicked: false,
    },
    // Add more options
  ]);

  return (
    // This might change depending if you want to use the storybook plugin
    <div style={{ maxWidth: "350px" }}>
      <InOutTextarea
        {...props}
        inValue={inValue}
        onInInput={(newValue) => setInValue(newValue)}
        inOptions={inOptions}
        onInOptionsUpdate={(newInOptions) => {
          setInOptions(newInOptions);
        }}
        outOptions={outOptions}
        onOutOptionsUpdate={(newOutOptions) => {
          setOutOptions(newOutOptions);
        }}
        outValue={"Hello"}
      />
    </div>
  );
};
```

## Resources

* [Storybook Viewport](https://storybook.js.org/docs/react/essentials/viewport)

## Files involved

- [`./stories/Thing.stories.tsx`](https://github.com/igeligel/react-in-out-textarea/blob/master/stories/Thing.stories.tsx)

**Comment by rohitgeddam** [comment]
I would like to work on this issue.
