### ISSUE TITLE
Feature: Mobile Textareas

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#70]
## Type of Feature

- [ ] API Extension
- [X] UI Feature
- [ ] other:

## How would it look like

The current state looks like this:

![chrome_2020-10-13_22-41-21](https://user-images.githubusercontent.com/12736734/95914111-8a8a0c80-0da5-11eb-8ab4-b3b591583c26.png)

The wanted state is something like this:

![chrome_2020-10-13_22-43-30](https://user-images.githubusercontent.com/12736734/95914138-9544a180-0da5-11eb-82f7-155034bbb0b7.png)

For this, you need to change the `flex-direction` from `flex-direction: row;` of `ConvertCardContent` to `flex-direction: column` when the content goes into a mobile layout. Mobile Layout here means below 720px. Please use media-queries to achieve this.

Otherwise the output/translated content wrapper (`TextAreaContent`) should have a background color of light gray (`background-color: hsl(0 0% 98% / 1);`).

```tsx
// src/TextAreaContent.tsx
import styled from "styled-components";

export const TextAreaContent = styled.div`
  flex: 1;
  padding-left: 28px;
  padding-top: 20px;
  padding-bottom: 42px;
  padding-right: 14px;
  width: 100%;
  box-sizing: border-box;
  display: flex;

  @media (max-width: 720px) {
    background-color: hsl(0 0% 98% / 1);
  }
`;

```tsx
// src/index.tsx
const ConvertCardContent = styled.div`
  width: 100%;
  display: flex;
  position: relative;

  @media (max-width: 720px) {
    flex-direction: column;
  }
`;

export const InOutTextarea: FC<Props> = (props) => {
  return (
    <>
      {/* ... */}
      <ConvertCardContent ref={convertCardRef}>
        {/* ... */}
        <TextAreaContent>{/* ... */}</TextAreaContent>
        <TextAreaContent>
          {/* ... */}
        </TextAreaContent>
      </ConvertCardContent>
    </>
  );
};
```

## Resources

* [Flexbox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

## Files involved

- [`./src/index.ts`](https://github.com/igeligel/react-in-out-textarea/blob/master/src/index.tsx)
- [`./src/TextAreaContent.tsx`](https://github.com/igeligel/react-in-out-textarea/blob/master/src/TextAreaContent.tsx)

**Comment by rohitgeddam** [comment]
i would like to work on it

**Comment by igeligel** [comment]
Hey @rohitgeddam, Thanks for reaching out. I will assign the ticket to you. If you have any question regarding the project, feel free to reach out to me.

**Comment by rohitgeddam** [comment]
Hey, @igeligel thanks for writing such a descriptive issue message. Please review my draft PR!
