### ISSUE TITLE
Feature: Custom Font

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#8]
## Type of Feature

- [X] API Extension
- [X] UI Feature
- [ ] other:

## How would it look like

A flag exists that makes it possible to pass a custom font. For example `monospace`.

```tsx
import React, { useState } from "react";
import { InOutTextarea, InOptions, OutOptions } from "react-in-out-textarea";
import { ThemeProvider } from "styled-components";

const theme = {
  font: "monospace"
};

export const ExampleComponent = () => {
  const [inValue, setInValue] = useState<string>("");
  const [outValue, setOutValue] = useState<string>("");
  const [inOptions, setInOptions] = useState<InOptions>([
    {
      name: "English",
      active: true
    },
    {
      name: "German",
      active: false
    }
  ]);
  const [outOptions, setOutOptions] = useState<OutOptions>([
    {
      name: "Chinese",
      active: true,
      activeClicked: false
    }
  ]);

  return (
    <ThemeProvider theme={theme}>
      <InOutTextarea
        inValue={inValue}
        outValue={outValue}
        onInInput={(newValue) => {
          setInValue(newValue);
          setOutValue(newValue);
        }}
        inOptions={inOptions}
        onInOptionsUpdate={(newInOptions) => {
          setInOptions(newInOptions);
        }}
        outOptions={outOptions}
        onOutOptionsUpdate={(newOutOptions) => {
          setOutOptions(newOutOptions);
        }}
      />
    </ThemeProvider>
  );
};
```

- Check the `font={"monospace"}` in the props of the component above.
- A storybook component is created for this case
- Another example in codesandbox will be created

## Resources

-/-

## Files involved

- [`./src/index.ts`](https://github.com/igeligel/react-in-out-textarea/blob/master/src/index.tsx)
- This can be implemented with the Theme functionality. Documentation can be found [here](https://styled-components.com/docs/advanced).

**Comment by merelj** [comment]
Haven't had a chance to work with Themes, would gladly help with this issue 👍

**Comment by igeligel** [comment]
@merelj assigned this issue to you now. Feel free to create a Pull Request. If you have any questions, feel free to reach out to me by commenting and tagging me. Cheers, Kev

**Comment by igeligel** [comment]
Created one follow up ticket: https://github.com/igeligel/react-in-out-textarea/issues/39
