### ISSUE TITLE
Documentation: Add "Mentioned In" section

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#80]
## What should be changed?

- [ ] An example is missing
- [ ] Existing documentation needs to be extended
- [X] Something else, state below: The `README.md` is extended

## Description

I wrote a blog article about this component that can be listed as material in the README. Create a new section in the README called "Mentioned in". It should be listed below "Used by" in the README and include a list. The first and only item should have the title of the [blog article that I wrote](https://www.kevinpeters.net/hacktoberfest-and-open-sourcing-a-react-js-component/) and should link it.

## Files involved

* `README.md`

**Comment by Emalsha** [comment]
Done 👍
