### ISSUE TITLE
Refactoring CaseBar

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#9]
## Type of Change

- [ ] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [X] Extract React/JavaScript/TypeScript component
- [ ] Remove duplicate code

## Description

Refactor the CaseBar into an own file called `CaseBar.ts`.

## Code Before

```tsx
const CaseBar = styled.div`
  border-bottom: ${props =>
    props.theme.main === 'dark'
      ? '1px solid rgba(229, 229, 229, 0.2)'
      : '1px solid rgba(20, 33, 61, 0.2)'};
  display: flex;
  @media (max-width: 576px) {
    flex-direction: column;
  }
`;
```

## Code Expected after Refactoring

```tsx
export const CaseBar = styled.div`
  border-bottom: ${props =>
    props.theme.main === 'dark'
      ? '1px solid rgba(229, 229, 229, 0.2)'
      : '1px solid rgba(20, 33, 61, 0.2)'};
  display: flex;
  @media (max-width: 576px) {
    flex-direction: column;
  }
`;
```

## Files involved

* `./src/index.tsx`
* `./src/CaseBar.ts` (need to be created)

**Comment by SheW0lf** [comment]
🍰 I'll take it!

**Comment by igeligel** [comment]
Thanks a lot 👍 Feel free to create a Pull Request. If you have any trouble, feel free to contact me.
