### ISSUE TITLE
Feature: Auto Close Menu

### ISSUE THREAD

**Issue by igeligel** [igeligel/react-in-out-textarea#93]
## Type of Feature

- [X] API Extension
- [X] UI Feature
- [ ] other:

## How would it look like

When selecting an input or output option the menu should self-close by default.

Alternatively, an option can be passed to the component that enables or disables this option. This option should be called `autoCloseMenuOnOptionSelection`.

## Resources

* -/-

## Files involved

- N/A

**Comment by binkpitch** [comment]
Can I work on this?

**Comment by igeligel** [comment]
Hey @binkpitch For sure you can work on this. I will assign the issue to you. If you have any questions feel free to ask me. Some guidance:

1. You probably want to extend the file [OptionsOverlay.tsx](https://github.com/igeligel/react-in-out-textarea/blob/master/src/OptionsOverlay.tsx) and pass an onClick handler from `index.tsx`
2. From index.tsx you can close the state of the overlay then.

Thanks a lot for wanting to work on this!
